version: "~> 1.0"
language: node_js
node_js:
- 8.16.2
install:
- npm install -g codecov
before_script:
- npm install
script:
- npm run build
- npm run coverage
- codecov --disable=gcov
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: QM7V5vW/2kAjYvxcV5hGvJvW57cTmS7w9kvLufDxqzTJhZPqS+F1VNrShiWGu66lo0bdCbOPjw+Yjf4th9Bx+TZoLLrayjbGE36WzQQvZ1bnQTezMVPKljgWNomrPOAgySQkpDhEusREnVzz2jsFJ6q6unYAED7ZVSQtev2nqym91EdQZo1RVvjoUv5Gsizdcm9X+KRiGG2O5Tj6lo+SzVEN53wEztSFwyyZpMGXPXnKZg0f2lSV05tyVTauVk+QpHISJtQ1OW+lQ/So/ztGNaegUbvz5DiiVzDeTMsqpKHCa7wSBbsgwUM74C2ywUkPdEsNtd1lyclqj3YVqEZO/z+vmVlncHD3YgIx1ipHFkP5apZ1nkP8RpUyb7EWEa/CNZuMH46xb1UkgC5pPv5NR8xKtN+5e4Co9tS4UekaN6zIuayxPIy8/O3HXAoIG7IMnod6+DtKbUVKdmpq+7kIKLGjflfQrCb8Znj26Lq2NJ68yVtwS6fgdQaZSyMd+3aHxlDd1yYzWlpzOPwFwS75/ETMRlMsu6VqzBmBxlCOWj1L2E8sA8UCR3wn+rfuLXMUPiKgog7XE2T5zmFTbSlLtRTNQN0gTjtfNw+IM/Y/7A5w3bu7b+8QpkAAR/b+hbXJFGGIBimqnASUOcKkaALE4KwK6BJQ1uI7oX7dA/a1MSw=
