version: "~> 1.0"
language: node_js
node_js:
- 8.16.2
install:
- npm install -g codecov
before_script:
- npm install
script:
- npm run build
- npm run coverage
- codecov --disable=gcov
notifications:
  slack:
    on_failure: always
    on_pull_requests: true
    on_success: always
    rooms:
      secure: ERUiV7jfZ+HW9Qn93kfV55mAFru/YYflCRxCRl1/RrPU5R4mlNJI9dm5V5MqA2WW1bAtMjp+QcOwDJQXRhXlo4oM2ZgWvEGGMPrP+7x3PZ1MPI0qTQ92d+zPh9f51e/LEmMiS/msKp7RHuaRVlNf78kqIhy4eQP58M7pd8hyByoCKdWgls4YSsdOLtFkcWvrDB7pBi06eEAOjSlMKk2Prhfmz0dc/6a7thdimY83DzKgX4gIKkK2sOeeAk7ik1WMqnFijRSIaoStOk9eK2unww9qRnADopcwMOAqF45/rOXeJLgDtkA7Od66KwcoBw98wQtjOkakc/TUqXaI2wKjL1P0XXsJU0KoNlEn8k9JWVhx9Z+D6YSWh6CBvUNAekF9L45IsEmWW8Vj5bCFJQwJNrulgEoVztPX2tToqgW+2B6vS67hjPd5PG32/fXf4Yysp1oBH1yDjKDo7KoGlpUZ/iAv6JAN6tEnt06Y5TLYe3V8yAWu1dM36Wj+pw9ih04Z7RUnpFd2lS2x8vcrOj0rEuKh4a4hm013B82HP2UAFauI10w0AIWX6wK4D3tMa8P19qCKMmsO2wREJTTocP8nHb7ulpoefYDOke71EvNbMnVyJAKeEdaDN2qMq5N7z8DGWwMeq6Edd5Jgmc7+fiFswNErsOb3/9h1l9R4UoQlaAQ=
